#################################### common config : ####################################
spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: development
  messages:
    basename: i18n/messages


comment.avatar: /images/carGirl.jpg
